apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30090    # NodePort 범위(30000~32767)
