apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: go-server
  ports:
    - name: http
      port: 8090
      targetPort: 8090
