apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: go-server
  ports:
    - name: http
      port: 8090           # Service가 노출하는 포트
      targetPort: 8090     # 컨테이너 내부 포트
