apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: webui
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - image: nginx
        name: nginx
