apiVersion: v1
kind: Service
metadata:
  name: webui-clusterip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
